# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/foronoma/Work/Code/Eurorack/performer-phazer

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/foronoma/Work/Code/Eurorack/performer-phazer

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	/opt/homebrew/bin/ctest $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/foronoma/Work/Code/Eurorack/performer-phazer/CMakeFiles /Users/foronoma/Work/Code/Eurorack/performer-phazer//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/foronoma/Work/Code/Eurorack/performer-phazer/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named core

# Build rule for target.
core: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 core
.PHONY : core

# fast build rule for target.
core/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/core.dir/build.make src/CMakeFiles/core.dir/build
.PHONY : core/fast

#=============================================================================
# Target rules for targets named rtmidi

# Build rule for target.
rtmidi: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 rtmidi
.PHONY : rtmidi

# fast build rule for target.
rtmidi/fast:
	$(MAKE) $(MAKESILENT) -f src/platform/sim/libs/rtmidi/CMakeFiles/rtmidi.dir/build.make src/platform/sim/libs/rtmidi/CMakeFiles/rtmidi.dir/build
.PHONY : rtmidi/fast

#=============================================================================
# Target rules for targets named sequencer_shared

# Build rule for target.
sequencer_shared: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sequencer_shared
.PHONY : sequencer_shared

# fast build rule for target.
sequencer_shared/fast:
	$(MAKE) $(MAKESILENT) -f src/apps/sequencer/CMakeFiles/sequencer_shared.dir/build.make src/apps/sequencer/CMakeFiles/sequencer_shared.dir/build
.PHONY : sequencer_shared/fast

#=============================================================================
# Target rules for targets named sequencer

# Build rule for target.
sequencer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sequencer
.PHONY : sequencer

# fast build rule for target.
sequencer/fast:
	$(MAKE) $(MAKESILENT) -f src/apps/sequencer/CMakeFiles/sequencer.dir/build.make src/apps/sequencer/CMakeFiles/sequencer.dir/build
.PHONY : sequencer/fast

#=============================================================================
# Target rules for targets named testsim

# Build rule for target.
testsim: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 testsim
.PHONY : testsim

# fast build rule for target.
testsim/fast:
	$(MAKE) $(MAKESILENT) -f src/apps/sequencer/python/CMakeFiles/testsim.dir/build.make src/apps/sequencer/python/CMakeFiles/testsim.dir/build
.PHONY : testsim/fast

#=============================================================================
# Target rules for targets named TestButtonLedMatrix

# Build rule for target.
TestButtonLedMatrix: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TestButtonLedMatrix
.PHONY : TestButtonLedMatrix

# fast build rule for target.
TestButtonLedMatrix/fast:
	$(MAKE) $(MAKESILENT) -f src/tests/integration/CMakeFiles/TestButtonLedMatrix.dir/build.make src/tests/integration/CMakeFiles/TestButtonLedMatrix.dir/build
.PHONY : TestButtonLedMatrix/fast

#=============================================================================
# Target rules for targets named TestAdc

# Build rule for target.
TestAdc: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TestAdc
.PHONY : TestAdc

# fast build rule for target.
TestAdc/fast:
	$(MAKE) $(MAKESILENT) -f src/tests/integration/CMakeFiles/TestAdc.dir/build.make src/tests/integration/CMakeFiles/TestAdc.dir/build
.PHONY : TestAdc/fast

#=============================================================================
# Target rules for targets named TestDac

# Build rule for target.
TestDac: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TestDac
.PHONY : TestDac

# fast build rule for target.
TestDac/fast:
	$(MAKE) $(MAKESILENT) -f src/tests/integration/CMakeFiles/TestDac.dir/build.make src/tests/integration/CMakeFiles/TestDac.dir/build
.PHONY : TestDac/fast

#=============================================================================
# Target rules for targets named TestDio

# Build rule for target.
TestDio: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TestDio
.PHONY : TestDio

# fast build rule for target.
TestDio/fast:
	$(MAKE) $(MAKESILENT) -f src/tests/integration/CMakeFiles/TestDio.dir/build.make src/tests/integration/CMakeFiles/TestDio.dir/build
.PHONY : TestDio/fast

#=============================================================================
# Target rules for targets named TestEncoder

# Build rule for target.
TestEncoder: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TestEncoder
.PHONY : TestEncoder

# fast build rule for target.
TestEncoder/fast:
	$(MAKE) $(MAKESILENT) -f src/tests/integration/CMakeFiles/TestEncoder.dir/build.make src/tests/integration/CMakeFiles/TestEncoder.dir/build
.PHONY : TestEncoder/fast

#=============================================================================
# Target rules for targets named TestGateOutput

# Build rule for target.
TestGateOutput: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TestGateOutput
.PHONY : TestGateOutput

# fast build rule for target.
TestGateOutput/fast:
	$(MAKE) $(MAKESILENT) -f src/tests/integration/CMakeFiles/TestGateOutput.dir/build.make src/tests/integration/CMakeFiles/TestGateOutput.dir/build
.PHONY : TestGateOutput/fast

#=============================================================================
# Target rules for targets named TestLcd

# Build rule for target.
TestLcd: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TestLcd
.PHONY : TestLcd

# fast build rule for target.
TestLcd/fast:
	$(MAKE) $(MAKESILENT) -f src/tests/integration/CMakeFiles/TestLcd.dir/build.make src/tests/integration/CMakeFiles/TestLcd.dir/build
.PHONY : TestLcd/fast

#=============================================================================
# Target rules for targets named TestMidi

# Build rule for target.
TestMidi: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TestMidi
.PHONY : TestMidi

# fast build rule for target.
TestMidi/fast:
	$(MAKE) $(MAKESILENT) -f src/tests/integration/CMakeFiles/TestMidi.dir/build.make src/tests/integration/CMakeFiles/TestMidi.dir/build
.PHONY : TestMidi/fast

#=============================================================================
# Target rules for targets named TestSdCard

# Build rule for target.
TestSdCard: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TestSdCard
.PHONY : TestSdCard

# fast build rule for target.
TestSdCard/fast:
	$(MAKE) $(MAKESILENT) -f src/tests/integration/CMakeFiles/TestSdCard.dir/build.make src/tests/integration/CMakeFiles/TestSdCard.dir/build
.PHONY : TestSdCard/fast

#=============================================================================
# Target rules for targets named TestUsbMidi

# Build rule for target.
TestUsbMidi: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TestUsbMidi
.PHONY : TestUsbMidi

# fast build rule for target.
TestUsbMidi/fast:
	$(MAKE) $(MAKESILENT) -f src/tests/integration/CMakeFiles/TestUsbMidi.dir/build.make src/tests/integration/CMakeFiles/TestUsbMidi.dir/build
.PHONY : TestUsbMidi/fast

#=============================================================================
# Target rules for targets named TestFileSystem

# Build rule for target.
TestFileSystem: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TestFileSystem
.PHONY : TestFileSystem

# fast build rule for target.
TestFileSystem/fast:
	$(MAKE) $(MAKESILENT) -f src/tests/integration/CMakeFiles/TestFileSystem.dir/build.make src/tests/integration/CMakeFiles/TestFileSystem.dir/build
.PHONY : TestFileSystem/fast

#=============================================================================
# Target rules for targets named TestSerialization

# Build rule for target.
TestSerialization: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TestSerialization
.PHONY : TestSerialization

# fast build rule for target.
TestSerialization/fast:
	$(MAKE) $(MAKESILENT) -f src/tests/unit/core/io/CMakeFiles/TestSerialization.dir/build.make src/tests/unit/core/io/CMakeFiles/TestSerialization.dir/build
.PHONY : TestSerialization/fast

#=============================================================================
# Target rules for targets named TestVersionedSerialization

# Build rule for target.
TestVersionedSerialization: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TestVersionedSerialization
.PHONY : TestVersionedSerialization

# fast build rule for target.
TestVersionedSerialization/fast:
	$(MAKE) $(MAKESILENT) -f src/tests/unit/core/io/CMakeFiles/TestVersionedSerialization.dir/build.make src/tests/unit/core/io/CMakeFiles/TestVersionedSerialization.dir/build
.PHONY : TestVersionedSerialization/fast

#=============================================================================
# Target rules for targets named TestMovingAverage

# Build rule for target.
TestMovingAverage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TestMovingAverage
.PHONY : TestMovingAverage

# fast build rule for target.
TestMovingAverage/fast:
	$(MAKE) $(MAKESILENT) -f src/tests/unit/core/utils/CMakeFiles/TestMovingAverage.dir/build.make src/tests/unit/core/utils/CMakeFiles/TestMovingAverage.dir/build
.PHONY : TestMovingAverage/fast

#=============================================================================
# Target rules for targets named TestObjectPool

# Build rule for target.
TestObjectPool: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TestObjectPool
.PHONY : TestObjectPool

# fast build rule for target.
TestObjectPool/fast:
	$(MAKE) $(MAKESILENT) -f src/tests/unit/core/utils/CMakeFiles/TestObjectPool.dir/build.make src/tests/unit/core/utils/CMakeFiles/TestObjectPool.dir/build
.PHONY : TestObjectPool/fast

#=============================================================================
# Target rules for targets named TestRandom

# Build rule for target.
TestRandom: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TestRandom
.PHONY : TestRandom

# fast build rule for target.
TestRandom/fast:
	$(MAKE) $(MAKESILENT) -f src/tests/unit/core/utils/CMakeFiles/TestRandom.dir/build.make src/tests/unit/core/utils/CMakeFiles/TestRandom.dir/build
.PHONY : TestRandom/fast

#=============================================================================
# Target rules for targets named TestStringUtils

# Build rule for target.
TestStringUtils: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TestStringUtils
.PHONY : TestStringUtils

# fast build rule for target.
TestStringUtils/fast:
	$(MAKE) $(MAKESILENT) -f src/tests/unit/core/utils/CMakeFiles/TestStringUtils.dir/build.make src/tests/unit/core/utils/CMakeFiles/TestStringUtils.dir/build
.PHONY : TestStringUtils/fast

#=============================================================================
# Target rules for targets named TestCurve

# Build rule for target.
TestCurve: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TestCurve
.PHONY : TestCurve

# fast build rule for target.
TestCurve/fast:
	$(MAKE) $(MAKESILENT) -f src/tests/unit/sequencer/CMakeFiles/TestCurve.dir/build.make src/tests/unit/sequencer/CMakeFiles/TestCurve.dir/build
.PHONY : TestCurve/fast

#=============================================================================
# Target rules for targets named TestCurveTrack

# Build rule for target.
TestCurveTrack: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TestCurveTrack
.PHONY : TestCurveTrack

# fast build rule for target.
TestCurveTrack/fast:
	$(MAKE) $(MAKESILENT) -f src/tests/unit/sequencer/CMakeFiles/TestCurveTrack.dir/build.make src/tests/unit/sequencer/CMakeFiles/TestCurveTrack.dir/build
.PHONY : TestCurveTrack/fast

#=============================================================================
# Target rules for targets named TestCurveTrackSerialization

# Build rule for target.
TestCurveTrackSerialization: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TestCurveTrackSerialization
.PHONY : TestCurveTrackSerialization

# fast build rule for target.
TestCurveTrackSerialization/fast:
	$(MAKE) $(MAKESILENT) -f src/tests/unit/sequencer/CMakeFiles/TestCurveTrackSerialization.dir/build.make src/tests/unit/sequencer/CMakeFiles/TestCurveTrackSerialization.dir/build
.PHONY : TestCurveTrackSerialization/fast

#=============================================================================
# Target rules for targets named TestScale

# Build rule for target.
TestScale: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TestScale
.PHONY : TestScale

# fast build rule for target.
TestScale/fast:
	$(MAKE) $(MAKESILENT) -f src/tests/unit/sequencer/CMakeFiles/TestScale.dir/build.make src/tests/unit/sequencer/CMakeFiles/TestScale.dir/build
.PHONY : TestScale/fast

#=============================================================================
# Target rules for targets named TestAccumulator

# Build rule for target.
TestAccumulator: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TestAccumulator
.PHONY : TestAccumulator

# fast build rule for target.
TestAccumulator/fast:
	$(MAKE) $(MAKESILENT) -f src/tests/unit/sequencer/CMakeFiles/TestAccumulator.dir/build.make src/tests/unit/sequencer/CMakeFiles/TestAccumulator.dir/build
.PHONY : TestAccumulator/fast

#=============================================================================
# Target rules for targets named TestAccumulatorSerialization

# Build rule for target.
TestAccumulatorSerialization: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TestAccumulatorSerialization
.PHONY : TestAccumulatorSerialization

# fast build rule for target.
TestAccumulatorSerialization/fast:
	$(MAKE) $(MAKESILENT) -f src/tests/unit/sequencer/CMakeFiles/TestAccumulatorSerialization.dir/build.make src/tests/unit/sequencer/CMakeFiles/TestAccumulatorSerialization.dir/build
.PHONY : TestAccumulatorSerialization/fast

#=============================================================================
# Target rules for targets named TestNoteSequence

# Build rule for target.
TestNoteSequence: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TestNoteSequence
.PHONY : TestNoteSequence

# fast build rule for target.
TestNoteSequence/fast:
	$(MAKE) $(MAKESILENT) -f src/tests/unit/sequencer/CMakeFiles/TestNoteSequence.dir/build.make src/tests/unit/sequencer/CMakeFiles/TestNoteSequence.dir/build
.PHONY : TestNoteSequence/fast

#=============================================================================
# Target rules for targets named TestPulseCount

# Build rule for target.
TestPulseCount: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TestPulseCount
.PHONY : TestPulseCount

# fast build rule for target.
TestPulseCount/fast:
	$(MAKE) $(MAKESILENT) -f src/tests/unit/sequencer/CMakeFiles/TestPulseCount.dir/build.make src/tests/unit/sequencer/CMakeFiles/TestPulseCount.dir/build
.PHONY : TestPulseCount/fast

#=============================================================================
# Target rules for targets named TestGateMode

# Build rule for target.
TestGateMode: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TestGateMode
.PHONY : TestGateMode

# fast build rule for target.
TestGateMode/fast:
	$(MAKE) $(MAKESILENT) -f src/tests/unit/sequencer/CMakeFiles/TestGateMode.dir/build.make src/tests/unit/sequencer/CMakeFiles/TestGateMode.dir/build
.PHONY : TestGateMode/fast

#=============================================================================
# Target rules for targets named TestGateStruct

# Build rule for target.
TestGateStruct: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TestGateStruct
.PHONY : TestGateStruct

# fast build rule for target.
TestGateStruct/fast:
	$(MAKE) $(MAKESILENT) -f src/tests/unit/sequencer/CMakeFiles/TestGateStruct.dir/build.make src/tests/unit/sequencer/CMakeFiles/TestGateStruct.dir/build
.PHONY : TestGateStruct/fast

#=============================================================================
# Target rules for targets named TestRTrigAccumTicking

# Build rule for target.
TestRTrigAccumTicking: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TestRTrigAccumTicking
.PHONY : TestRTrigAccumTicking

# fast build rule for target.
TestRTrigAccumTicking/fast:
	$(MAKE) $(MAKESILENT) -f src/tests/unit/sequencer/CMakeFiles/TestRTrigAccumTicking.dir/build.make src/tests/unit/sequencer/CMakeFiles/TestRTrigAccumTicking.dir/build
.PHONY : TestRTrigAccumTicking/fast

#=============================================================================
# Target rules for targets named TestRTrigEdgeCases

# Build rule for target.
TestRTrigEdgeCases: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TestRTrigEdgeCases
.PHONY : TestRTrigEdgeCases

# fast build rule for target.
TestRTrigEdgeCases/fast:
	$(MAKE) $(MAKESILENT) -f src/tests/unit/sequencer/CMakeFiles/TestRTrigEdgeCases.dir/build.make src/tests/unit/sequencer/CMakeFiles/TestRTrigEdgeCases.dir/build
.PHONY : TestRTrigEdgeCases/fast

#=============================================================================
# Target rules for targets named TestCompilationFlags

# Build rule for target.
TestCompilationFlags: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TestCompilationFlags
.PHONY : TestCompilationFlags

# fast build rule for target.
TestCompilationFlags/fast:
	$(MAKE) $(MAKESILENT) -f src/tests/unit/sequencer/CMakeFiles/TestCompilationFlags.dir/build.make src/tests/unit/sequencer/CMakeFiles/TestCompilationFlags.dir/build
.PHONY : TestCompilationFlags/fast

#=============================================================================
# Target rules for targets named TestHarmonyEngine

# Build rule for target.
TestHarmonyEngine: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TestHarmonyEngine
.PHONY : TestHarmonyEngine

# fast build rule for target.
TestHarmonyEngine/fast:
	$(MAKE) $(MAKESILENT) -f src/tests/unit/sequencer/CMakeFiles/TestHarmonyEngine.dir/build.make src/tests/unit/sequencer/CMakeFiles/TestHarmonyEngine.dir/build
.PHONY : TestHarmonyEngine/fast

#=============================================================================
# Target rules for targets named TestHarmonyIntegration

# Build rule for target.
TestHarmonyIntegration: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TestHarmonyIntegration
.PHONY : TestHarmonyIntegration

# fast build rule for target.
TestHarmonyIntegration/fast:
	$(MAKE) $(MAKESILENT) -f src/tests/unit/sequencer/CMakeFiles/TestHarmonyIntegration.dir/build.make src/tests/unit/sequencer/CMakeFiles/TestHarmonyIntegration.dir/build
.PHONY : TestHarmonyIntegration/fast

#=============================================================================
# Target rules for targets named TestHarmonyInversionIssue

# Build rule for target.
TestHarmonyInversionIssue: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TestHarmonyInversionIssue
.PHONY : TestHarmonyInversionIssue

# fast build rule for target.
TestHarmonyInversionIssue/fast:
	$(MAKE) $(MAKESILENT) -f src/tests/unit/sequencer/CMakeFiles/TestHarmonyInversionIssue.dir/build.make src/tests/unit/sequencer/CMakeFiles/TestHarmonyInversionIssue.dir/build
.PHONY : TestHarmonyInversionIssue/fast

#=============================================================================
# Target rules for targets named TestHarmonyInversionBug

# Build rule for target.
TestHarmonyInversionBug: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TestHarmonyInversionBug
.PHONY : TestHarmonyInversionBug

# fast build rule for target.
TestHarmonyInversionBug/fast:
	$(MAKE) $(MAKESILENT) -f src/tests/unit/sequencer/CMakeFiles/TestHarmonyInversionBug.dir/build.make src/tests/unit/sequencer/CMakeFiles/TestHarmonyInversionBug.dir/build
.PHONY : TestHarmonyInversionBug/fast

#=============================================================================
# Target rules for targets named TestHarmonyVoicing

# Build rule for target.
TestHarmonyVoicing: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TestHarmonyVoicing
.PHONY : TestHarmonyVoicing

# fast build rule for target.
TestHarmonyVoicing/fast:
	$(MAKE) $(MAKESILENT) -f src/tests/unit/sequencer/CMakeFiles/TestHarmonyVoicing.dir/build.make src/tests/unit/sequencer/CMakeFiles/TestHarmonyVoicing.dir/build
.PHONY : TestHarmonyVoicing/fast

#=============================================================================
# Target rules for targets named TestModel

# Build rule for target.
TestModel: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TestModel
.PHONY : TestModel

# fast build rule for target.
TestModel/fast:
	$(MAKE) $(MAKESILENT) -f src/tests/unit/sequencer/CMakeFiles/TestModel.dir/build.make src/tests/unit/sequencer/CMakeFiles/TestModel.dir/build
.PHONY : TestModel/fast

#=============================================================================
# Target rules for targets named TestTuesdayTrack

# Build rule for target.
TestTuesdayTrack: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TestTuesdayTrack
.PHONY : TestTuesdayTrack

# fast build rule for target.
TestTuesdayTrack/fast:
	$(MAKE) $(MAKESILENT) -f src/tests/unit/sequencer/CMakeFiles/TestTuesdayTrack.dir/build.make src/tests/unit/sequencer/CMakeFiles/TestTuesdayTrack.dir/build
.PHONY : TestTuesdayTrack/fast

#=============================================================================
# Target rules for targets named TestTuesdayTrackIntegration

# Build rule for target.
TestTuesdayTrackIntegration: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TestTuesdayTrackIntegration
.PHONY : TestTuesdayTrackIntegration

# fast build rule for target.
TestTuesdayTrackIntegration/fast:
	$(MAKE) $(MAKESILENT) -f src/tests/unit/sequencer/CMakeFiles/TestTuesdayTrackIntegration.dir/build.make src/tests/unit/sequencer/CMakeFiles/TestTuesdayTrackIntegration.dir/build
.PHONY : TestTuesdayTrackIntegration/fast

#=============================================================================
# Target rules for targets named TestTuesdayTrackEngine

# Build rule for target.
TestTuesdayTrackEngine: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TestTuesdayTrackEngine
.PHONY : TestTuesdayTrackEngine

# fast build rule for target.
TestTuesdayTrackEngine/fast:
	$(MAKE) $(MAKESILENT) -f src/tests/unit/sequencer/CMakeFiles/TestTuesdayTrackEngine.dir/build.make src/tests/unit/sequencer/CMakeFiles/TestTuesdayTrackEngine.dir/build
.PHONY : TestTuesdayTrackEngine/fast

#=============================================================================
# Target rules for targets named TestTuesdayTrackListModel

# Build rule for target.
TestTuesdayTrackListModel: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TestTuesdayTrackListModel
.PHONY : TestTuesdayTrackListModel

# fast build rule for target.
TestTuesdayTrackListModel/fast:
	$(MAKE) $(MAKESILENT) -f src/tests/unit/sequencer/CMakeFiles/TestTuesdayTrackListModel.dir/build.make src/tests/unit/sequencer/CMakeFiles/TestTuesdayTrackListModel.dir/build
.PHONY : TestTuesdayTrackListModel/fast

#=============================================================================
# Target rules for targets named TestTuesdayScaleQuantization

# Build rule for target.
TestTuesdayScaleQuantization: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TestTuesdayScaleQuantization
.PHONY : TestTuesdayScaleQuantization

# fast build rule for target.
TestTuesdayScaleQuantization/fast:
	$(MAKE) $(MAKESILENT) -f src/tests/unit/sequencer/CMakeFiles/TestTuesdayScaleQuantization.dir/build.make src/tests/unit/sequencer/CMakeFiles/TestTuesdayScaleQuantization.dir/build
.PHONY : TestTuesdayScaleQuantization/fast

#=============================================================================
# Target rules for targets named TestTuesdayAlgorithmNames

# Build rule for target.
TestTuesdayAlgorithmNames: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TestTuesdayAlgorithmNames
.PHONY : TestTuesdayAlgorithmNames

# fast build rule for target.
TestTuesdayAlgorithmNames/fast:
	$(MAKE) $(MAKESILENT) -f src/tests/unit/sequencer/CMakeFiles/TestTuesdayAlgorithmNames.dir/build.make src/tests/unit/sequencer/CMakeFiles/TestTuesdayAlgorithmNames.dir/build
.PHONY : TestTuesdayAlgorithmNames/fast

#=============================================================================
# Target rules for targets named TestTuesdayAlgorithmBuffers

# Build rule for target.
TestTuesdayAlgorithmBuffers: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TestTuesdayAlgorithmBuffers
.PHONY : TestTuesdayAlgorithmBuffers

# fast build rule for target.
TestTuesdayAlgorithmBuffers/fast:
	$(MAKE) $(MAKESILENT) -f src/tests/unit/sequencer/CMakeFiles/TestTuesdayAlgorithmBuffers.dir/build.make src/tests/unit/sequencer/CMakeFiles/TestTuesdayAlgorithmBuffers.dir/build
.PHONY : TestTuesdayAlgorithmBuffers/fast

#=============================================================================
# Target rules for targets named TestTuesdayAmbient

# Build rule for target.
TestTuesdayAmbient: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TestTuesdayAmbient
.PHONY : TestTuesdayAmbient

# fast build rule for target.
TestTuesdayAmbient/fast:
	$(MAKE) $(MAKESILENT) -f src/tests/unit/sequencer/CMakeFiles/TestTuesdayAmbient.dir/build.make src/tests/unit/sequencer/CMakeFiles/TestTuesdayAmbient.dir/build
.PHONY : TestTuesdayAmbient/fast

#=============================================================================
# Target rules for targets named TestTuesdayMinimal

# Build rule for target.
TestTuesdayMinimal: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TestTuesdayMinimal
.PHONY : TestTuesdayMinimal

# fast build rule for target.
TestTuesdayMinimal/fast:
	$(MAKE) $(MAKESILENT) -f src/tests/unit/sequencer/CMakeFiles/TestTuesdayMinimal.dir/build.make src/tests/unit/sequencer/CMakeFiles/TestTuesdayMinimal.dir/build
.PHONY : TestTuesdayMinimal/fast

#=============================================================================
# Target rules for targets named TestTuesdayDrill

# Build rule for target.
TestTuesdayDrill: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TestTuesdayDrill
.PHONY : TestTuesdayDrill

# fast build rule for target.
TestTuesdayDrill/fast:
	$(MAKE) $(MAKESILENT) -f src/tests/unit/sequencer/CMakeFiles/TestTuesdayDrill.dir/build.make src/tests/unit/sequencer/CMakeFiles/TestTuesdayDrill.dir/build
.PHONY : TestTuesdayDrill/fast

#=============================================================================
# Target rules for targets named TestTuesdayAcid

# Build rule for target.
TestTuesdayAcid: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TestTuesdayAcid
.PHONY : TestTuesdayAcid

# fast build rule for target.
TestTuesdayAcid/fast:
	$(MAKE) $(MAKESILENT) -f src/tests/unit/sequencer/CMakeFiles/TestTuesdayAcid.dir/build.make src/tests/unit/sequencer/CMakeFiles/TestTuesdayAcid.dir/build
.PHONY : TestTuesdayAcid/fast

#=============================================================================
# Target rules for targets named TestTuesdayKraft

# Build rule for target.
TestTuesdayKraft: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TestTuesdayKraft
.PHONY : TestTuesdayKraft

# fast build rule for target.
TestTuesdayKraft/fast:
	$(MAKE) $(MAKESILENT) -f src/tests/unit/sequencer/CMakeFiles/TestTuesdayKraft.dir/build.make src/tests/unit/sequencer/CMakeFiles/TestTuesdayKraft.dir/build
.PHONY : TestTuesdayKraft/fast

#=============================================================================
# Target rules for targets named TestTuesdayAphex

# Build rule for target.
TestTuesdayAphex: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TestTuesdayAphex
.PHONY : TestTuesdayAphex

# fast build rule for target.
TestTuesdayAphex/fast:
	$(MAKE) $(MAKESILENT) -f src/tests/unit/sequencer/CMakeFiles/TestTuesdayAphex.dir/build.make src/tests/unit/sequencer/CMakeFiles/TestTuesdayAphex.dir/build
.PHONY : TestTuesdayAphex/fast

#=============================================================================
# Target rules for targets named TestTuesdayAutech

# Build rule for target.
TestTuesdayAutech: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TestTuesdayAutech
.PHONY : TestTuesdayAutech

# fast build rule for target.
TestTuesdayAutech/fast:
	$(MAKE) $(MAKESILENT) -f src/tests/unit/sequencer/CMakeFiles/TestTuesdayAutech.dir/build.make src/tests/unit/sequencer/CMakeFiles/TestTuesdayAutech.dir/build
.PHONY : TestTuesdayAutech/fast

#=============================================================================
# Target rules for targets named TestTuesdayGateOffset

# Build rule for target.
TestTuesdayGateOffset: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TestTuesdayGateOffset
.PHONY : TestTuesdayGateOffset

# fast build rule for target.
TestTuesdayGateOffset/fast:
	$(MAKE) $(MAKESILENT) -f src/tests/unit/sequencer/CMakeFiles/TestTuesdayGateOffset.dir/build.make src/tests/unit/sequencer/CMakeFiles/TestTuesdayGateOffset.dir/build
.PHONY : TestTuesdayGateOffset/fast

#=============================================================================
# Target rules for targets named TestTuesdayPolyrhythm

# Build rule for target.
TestTuesdayPolyrhythm: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TestTuesdayPolyrhythm
.PHONY : TestTuesdayPolyrhythm

# fast build rule for target.
TestTuesdayPolyrhythm/fast:
	$(MAKE) $(MAKESILENT) -f src/tests/unit/sequencer/CMakeFiles/TestTuesdayPolyrhythm.dir/build.make src/tests/unit/sequencer/CMakeFiles/TestTuesdayPolyrhythm.dir/build
.PHONY : TestTuesdayPolyrhythm/fast

#=============================================================================
# Target rules for targets named TestTuesdayTrackGateOffset

# Build rule for target.
TestTuesdayTrackGateOffset: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TestTuesdayTrackGateOffset
.PHONY : TestTuesdayTrackGateOffset

# fast build rule for target.
TestTuesdayTrackGateOffset/fast:
	$(MAKE) $(MAKESILENT) -f src/tests/unit/sequencer/CMakeFiles/TestTuesdayTrackGateOffset.dir/build.make src/tests/unit/sequencer/CMakeFiles/TestTuesdayTrackGateOffset.dir/build
.PHONY : TestTuesdayTrackGateOffset/fast

#=============================================================================
# Target rules for targets named TestTuesdayTrackEngineGateOffset

# Build rule for target.
TestTuesdayTrackEngineGateOffset: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TestTuesdayTrackEngineGateOffset
.PHONY : TestTuesdayTrackEngineGateOffset

# fast build rule for target.
TestTuesdayTrackEngineGateOffset/fast:
	$(MAKE) $(MAKESILENT) -f src/tests/unit/sequencer/CMakeFiles/TestTuesdayTrackEngineGateOffset.dir/build.make src/tests/unit/sequencer/CMakeFiles/TestTuesdayTrackEngineGateOffset.dir/build
.PHONY : TestTuesdayTrackEngineGateOffset/fast

#=============================================================================
# Target rules for targets named TestCurveTrackLfoShapes

# Build rule for target.
TestCurveTrackLfoShapes: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TestCurveTrackLfoShapes
.PHONY : TestCurveTrackLfoShapes

# fast build rule for target.
TestCurveTrackLfoShapes/fast:
	$(MAKE) $(MAKESILENT) -f src/tests/unit/sequencer/CMakeFiles/TestCurveTrackLfoShapes.dir/build.make src/tests/unit/sequencer/CMakeFiles/TestCurveTrackLfoShapes.dir/build
.PHONY : TestCurveTrackLfoShapes/fast

#=============================================================================
# Target rules for targets named TestCurveTrackLfoShapesIntegration

# Build rule for target.
TestCurveTrackLfoShapesIntegration: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TestCurveTrackLfoShapesIntegration
.PHONY : TestCurveTrackLfoShapesIntegration

# fast build rule for target.
TestCurveTrackLfoShapesIntegration/fast:
	$(MAKE) $(MAKESILENT) -f src/tests/unit/sequencer/CMakeFiles/TestCurveTrackLfoShapesIntegration.dir/build.make src/tests/unit/sequencer/CMakeFiles/TestCurveTrackLfoShapesIntegration.dir/build
.PHONY : TestCurveTrackLfoShapesIntegration/fast

#=============================================================================
# Target rules for targets named TestCurveTrackEnginePhase

# Build rule for target.
TestCurveTrackEnginePhase: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TestCurveTrackEnginePhase
.PHONY : TestCurveTrackEnginePhase

# fast build rule for target.
TestCurveTrackEnginePhase/fast:
	$(MAKE) $(MAKESILENT) -f src/tests/unit/sequencer/CMakeFiles/TestCurveTrackEnginePhase.dir/build.make src/tests/unit/sequencer/CMakeFiles/TestCurveTrackEnginePhase.dir/build
.PHONY : TestCurveTrackEnginePhase/fast

#=============================================================================
# Target rules for targets named TestCurveTrackEngineGlobalPhase

# Build rule for target.
TestCurveTrackEngineGlobalPhase: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TestCurveTrackEngineGlobalPhase
.PHONY : TestCurveTrackEngineGlobalPhase

# fast build rule for target.
TestCurveTrackEngineGlobalPhase/fast:
	$(MAKE) $(MAKESILENT) -f src/tests/unit/sequencer/CMakeFiles/TestCurveTrackEngineGlobalPhase.dir/build.make src/tests/unit/sequencer/CMakeFiles/TestCurveTrackEngineGlobalPhase.dir/build
.PHONY : TestCurveTrackEngineGlobalPhase/fast

#=============================================================================
# Target rules for targets named TestOutputRotation

# Build rule for target.
TestOutputRotation: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TestOutputRotation
.PHONY : TestOutputRotation

# fast build rule for target.
TestOutputRotation/fast:
	$(MAKE) $(MAKESILENT) -f src/tests/unit/sequencer/CMakeFiles/TestOutputRotation.dir/build.make src/tests/unit/sequencer/CMakeFiles/TestOutputRotation.dir/build
.PHONY : TestOutputRotation/fast

#=============================================================================
# Target rules for targets named TestCurveTrackPatterns

# Build rule for target.
TestCurveTrackPatterns: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TestCurveTrackPatterns
.PHONY : TestCurveTrackPatterns

# fast build rule for target.
TestCurveTrackPatterns/fast:
	$(MAKE) $(MAKESILENT) -f src/tests/unit/sequencer/CMakeFiles/TestCurveTrackPatterns.dir/build.make src/tests/unit/sequencer/CMakeFiles/TestCurveTrackPatterns.dir/build
.PHONY : TestCurveTrackPatterns/fast

#=============================================================================
# Target rules for targets named TestTuesdayTrackPatterns

# Build rule for target.
TestTuesdayTrackPatterns: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TestTuesdayTrackPatterns
.PHONY : TestTuesdayTrackPatterns

# fast build rule for target.
TestTuesdayTrackPatterns/fast:
	$(MAKE) $(MAKESILENT) -f src/tests/unit/sequencer/CMakeFiles/TestTuesdayTrackPatterns.dir/build.make src/tests/unit/sequencer/CMakeFiles/TestTuesdayTrackPatterns.dir/build
.PHONY : TestTuesdayTrackPatterns/fast

#=============================================================================
# Target rules for targets named TestTuesdayRefactor

# Build rule for target.
TestTuesdayRefactor: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TestTuesdayRefactor
.PHONY : TestTuesdayRefactor

# fast build rule for target.
TestTuesdayRefactor/fast:
	$(MAKE) $(MAKESILENT) -f src/tests/unit/sequencer/CMakeFiles/TestTuesdayRefactor.dir/build.make src/tests/unit/sequencer/CMakeFiles/TestTuesdayRefactor.dir/build
.PHONY : TestTuesdayRefactor/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... TestAccumulator"
	@echo "... TestAccumulatorSerialization"
	@echo "... TestAdc"
	@echo "... TestButtonLedMatrix"
	@echo "... TestCompilationFlags"
	@echo "... TestCurve"
	@echo "... TestCurveTrack"
	@echo "... TestCurveTrackEngineGlobalPhase"
	@echo "... TestCurveTrackEnginePhase"
	@echo "... TestCurveTrackLfoShapes"
	@echo "... TestCurveTrackLfoShapesIntegration"
	@echo "... TestCurveTrackPatterns"
	@echo "... TestCurveTrackSerialization"
	@echo "... TestDac"
	@echo "... TestDio"
	@echo "... TestEncoder"
	@echo "... TestFileSystem"
	@echo "... TestGateMode"
	@echo "... TestGateOutput"
	@echo "... TestGateStruct"
	@echo "... TestHarmonyEngine"
	@echo "... TestHarmonyIntegration"
	@echo "... TestHarmonyInversionBug"
	@echo "... TestHarmonyInversionIssue"
	@echo "... TestHarmonyVoicing"
	@echo "... TestLcd"
	@echo "... TestMidi"
	@echo "... TestModel"
	@echo "... TestMovingAverage"
	@echo "... TestNoteSequence"
	@echo "... TestObjectPool"
	@echo "... TestOutputRotation"
	@echo "... TestPulseCount"
	@echo "... TestRTrigAccumTicking"
	@echo "... TestRTrigEdgeCases"
	@echo "... TestRandom"
	@echo "... TestScale"
	@echo "... TestSdCard"
	@echo "... TestSerialization"
	@echo "... TestStringUtils"
	@echo "... TestTuesdayAcid"
	@echo "... TestTuesdayAlgorithmBuffers"
	@echo "... TestTuesdayAlgorithmNames"
	@echo "... TestTuesdayAmbient"
	@echo "... TestTuesdayAphex"
	@echo "... TestTuesdayAutech"
	@echo "... TestTuesdayDrill"
	@echo "... TestTuesdayGateOffset"
	@echo "... TestTuesdayKraft"
	@echo "... TestTuesdayMinimal"
	@echo "... TestTuesdayPolyrhythm"
	@echo "... TestTuesdayRefactor"
	@echo "... TestTuesdayScaleQuantization"
	@echo "... TestTuesdayTrack"
	@echo "... TestTuesdayTrackEngine"
	@echo "... TestTuesdayTrackEngineGateOffset"
	@echo "... TestTuesdayTrackGateOffset"
	@echo "... TestTuesdayTrackIntegration"
	@echo "... TestTuesdayTrackListModel"
	@echo "... TestTuesdayTrackPatterns"
	@echo "... TestUsbMidi"
	@echo "... TestVersionedSerialization"
	@echo "... core"
	@echo "... rtmidi"
	@echo "... sequencer"
	@echo "... sequencer_shared"
	@echo "... testsim"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

