#!/usr/bin/env python3
"""Generate the native TT2 op/mod name registry (enum -> canonical name).

Source of truth is teletype/src/match_token.rl (the Ragel grammar Ragel compiles
forward, name->enum). This emits the reverse (enum->name) the native printer needs,
so names cannot drift from the lexer. No dependency on tele_ops[] / print_command.

Multiple spellings can map to one enum (e.g. W.ACT and WR.ACT -> E_OP_WR_ACT);
we keep the FIRST spelling seen per enum so the generated switch has one case each.

Regenerate:  python3 teletype/utils/tt2_op_names.py
"""

import re
from os import path

THIS_DIR = path.dirname(path.realpath(__file__))
REPO_ROOT = path.abspath(path.join(THIS_DIR, "..", ".."))
RL = path.join(REPO_ROOT, "teletype/src/match_token.rl")
OUT_DIR = path.join(REPO_ROOT, "src/apps/sequencer/engine")
OUT_H = path.join(OUT_DIR, "TT2OpNames.h")
OUT_CPP = path.join(OUT_DIR, "TT2OpNames.cpp")

LINE = re.compile(r'"([^"]+)"\s*=>\s*\{\s*MATCH_(OP|MOD)\(\s*(E_(?:OP|MOD)_\w+)\s*\)')


def collect():
    ops, mods = {}, {}          # enum -> first spelling (insertion-ordered dict)
    with open(RL) as f:
        for line in f:
            m = LINE.search(line)
            if not m:
                continue
            name, kind, enum = m.group(1), m.group(2), m.group(3)
            table = ops if kind == "OP" else mods
            if enum not in table:   # first spelling wins (alias dedup)
                table[enum] = name
    return ops, mods


def esc(s):
    return s.replace("\\", "\\\\").replace('"', '\\"')


def emit_switch(fn, table):
    out = [f"const char *{fn}(int v) {{", "    switch (v) {"]
    for enum, name in table.items():
        out.append(f'    case {enum}: return "{esc(name)}";')
    out.append("    default: return nullptr;")
    out.append("    }")
    out.append("}")
    return "\n".join(out)


def main():
    ops, mods = collect()
    header = (
        "#pragma once\n\n"
        "// GENERATED by teletype/utils/tt2_op_names.py from teletype/src/match_token.rl\n"
        "// Regenerate: python3 teletype/utils/tt2_op_names.py\n"
        "// Native enum->name registry for the TT2 printer (no tele_ops[]).\n\n"
        "const char *tt2OpName(int op);   // canonical spelling, or nullptr if out of range\n"
        "const char *tt2ModName(int mod);\n"
    )
    cpp = (
        "// GENERATED by teletype/utils/tt2_op_names.py from teletype/src/match_token.rl\n"
        "// Regenerate: python3 teletype/utils/tt2_op_names.py\n\n"
        '#include "TT2OpNames.h"\n\n'
        'extern "C" {\n'
        '#include "ops/op_enum.h"\n'
        "}\n\n"
        + emit_switch("tt2OpName", ops)
        + "\n\n"
        + emit_switch("tt2ModName", mods)
        + "\n"
    )
    with open(OUT_H, "w") as f:
        f.write(header)
    with open(OUT_CPP, "w") as f:
        f.write(cpp)
    print(f"ops={len(ops)} mods={len(mods)} -> {OUT_H}, {OUT_CPP}")


if __name__ == "__main__":
    main()
