#pragma once

// GENERATED by teletype/utils/tt2_op_names.py from teletype/src/match_token.rl
// Regenerate: python3 teletype/utils/tt2_op_names.py
// Native enum->name registry for the TT2 printer (no tele_ops[]).

const char *tt2OpName(int op);   // canonical spelling, or nullptr if out of range
const char *tt2ModName(int mod);
