#ifndef _SCRIPT_H_
#define _SCRIPT_H_

#include "teletype_config.h"

#ifndef REGULAR_SCRIPT_COUNT
#define REGULAR_SCRIPT_COUNT 8
#endif

#define METRO_SCRIPT REGULAR_SCRIPT_COUNT

#if TELETYPE_TRACK_LITE
#define EDITABLE_SCRIPT_COUNT (METRO_SCRIPT + 1)
#define DELAY_SCRIPT (EDITABLE_SCRIPT_COUNT)
#define TOTAL_SCRIPT_COUNT (DELAY_SCRIPT + 1)
#define NO_SCRIPT TOTAL_SCRIPT_COUNT
#define INIT_SCRIPT NO_SCRIPT
#define LIVE_SCRIPT NO_SCRIPT
#else
#define INIT_SCRIPT (METRO_SCRIPT + 1)
#define EDITABLE_SCRIPT_COUNT (INIT_SCRIPT + 1)
#define DELAY_SCRIPT (INIT_SCRIPT + 1)
#define LIVE_SCRIPT (DELAY_SCRIPT + 1)
#define TOTAL_SCRIPT_COUNT (LIVE_SCRIPT + 1)
#define NO_SCRIPT TOTAL_SCRIPT_COUNT
#endif

#endif
