#ifndef _TELETYPE_CONFIG_H_
#define _TELETYPE_CONFIG_H_

#ifndef TELETYPE_TRACK_LITE
#define TELETYPE_TRACK_LITE 1
#endif

#if TELETYPE_TRACK_LITE
#define DELAY_SIZE 16
#define REGULAR_SCRIPT_COUNT 4
#define GRID_GROUP_COUNT 1
#define GRID_MAX_DIMENSION 1
#define GRID_BUTTON_COUNT 1
#define GRID_FADER_COUNT 1
#define GRID_XYPAD_COUNT 1
#else
#define DELAY_SIZE 64
#define REGULAR_SCRIPT_COUNT 8
#define GRID_GROUP_COUNT 64
#define GRID_MAX_DIMENSION 16
#define GRID_BUTTON_COUNT 256
#define GRID_FADER_COUNT 64
#define GRID_XYPAD_COUNT 8
#endif

#endif
